### ISSUE TITLE
Incremental Meet Updates

### ISSUE THREAD

**Issue by denglender** [kippnorcal/google_classroom#100]
Pulling Google Meet data currently takes about 15 minutes for us, a relatively small network of schools.  For a mid- to large-sized network, this could take a extremely long time.

It's probably a good idea eventually to change the Meet logic to query only for new data since the last update, and append that to the table, rather than dropping the table and re-adding everything.

**Comment by dchess** [comment]
@denglender Thanks for flagging this. It does look like the admin activities report api does have optional parameters for filtering by start_date. So this should be possible to adjust similar to the usage report. @zkagin What do you think?

**Comment by zkagin** [comment]
Yep, this definitely seems doable. I can take a look at it next week. I think we've handled most of the edge cases with the usage report, so hopefully it is fairly straightforward.

**Comment by denglender** [comment]
Great!  Thanks both.

Also noting, this may obviate the need for #91 as it relates to Meet data, since if only adding the incremental data and not dropping the table, you won't have to worry about losing data due to the the six month rolling window on google's side.

**Comment by denglender** [comment]
Hi both - 

Update on this, it now takes about an hour for our Meet data to sync which is pretty unwieldy, and will get more so pretty quickly, I think.

@zkagin - Obviously would prefer your code on this to stumbling through myself, but if you think unlikely to be prioritized in the near future, I'll likely put some work on it at some point.  In that case, if you had any pointers from writing the usage report, would be all ears.

**Comment by zkagin** [comment]
Thanks for checking in on this @denglender. For some reason I thought this would be dependent on #99, but on further investigation it seems pretty straightforward to do directly. I just attached PR #112 to this, and hopefully we can get this to you soon. Feel free to patch and test it locally in the mean time.
