### ISSUE TITLE
Coursework endpoint failing

### ISSUE THREAD

**Issue by KTXDataSystems** [kippnorcal/google_classroom#114]
We're getting the following error now when trying to download coursework:

2020-12-08 01:16:47PM Central Standard Time | ERROR: (pyodbc.DataError) ('22018', '[22018] [Microsoft][ODBC Driver 13 for SQL Server]Invalid character value for cast specification (0) (SQLParamData)')
[SQL: INSERT INTO dbo.[GoogleClassroom_CourseWork] ([courseId], id, title, description, state, [alternateLink], [creationTime], [updateTime], [dueDate], [maxPoints], [workType], [assigneeMode], [submissionModificationMode], [creatorUserId], [topicId]) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (('222693886482', '223016268500', 'to do', None, 'PUBLISHED', 'https://classroom.google.com/c/MjIyNjkzODg2NDgy/a/MjIzMDE2MjY4NTAw/details', datetime.datetime(2020, 11, 11, 13, 29, 5, 499000), datetime.datetime(2020, 11, 11, 13, 31, 44, 627000), None, 100, 'ASSIGNMENT', 'ALL_STUDENTS', 'MODIFIABLE_UNTIL_TURNED_IN', '115624344439250234383', None), ('222693886482', '222718588596', 'class class', None, 'PUBLISHED', 'https://classroom.google.com/c/MjIyNjkzODg2NDgy/a/MjIyNzE4NTg4NTk2/details', datetime.datetime(2020, 11, 10, 20, 16, 31, 164000), datetime.datetime(2020, 11, 10, 20, 16, 44, 358000), None, 100, 'ASSIGNMENT', 'ALL_STUDENTS', 'MODIFIABLE_UNTIL_TURNED_IN', '115624344439250234383', None), ('222691921702', '232238999150', 'How much wood would a woodchuck chuck if a woodchuck could chuck wood?', 'ANSWER THE QUESTION!', 'PUBLISHED', 'https://classroom.google.com/c/MjIyNjkxOTIxNzAy/sa/MjMyMjM4OTk5MTUw/details', datetime.datetime(2020, 11, 19, 13, 44, 26, 403000), datetime.datetime(2020, 11, 19, 13, 48, 37, 97000), None, 70, 'SHORT_ANSWER_QUESTION', 'ALL_STUDENTS', 'MODIFIABLE_UNTIL_TURNED_IN', '104144867849088240281', None), ('222691921702', '228735845599', 'SPELL IT RIGHT!', 'You have to spell  all the questions right!', 'PUBLISHED', 'https://classroom.google.com/c/MjIyNjkxOTIxNzAy/a/MjI4NzM1ODQ1NTk5/details', datetime.datetime(2020, 11, 11, 15, 24, 38, 974000), datetime.datetime(2020, 11, 11, 15, 39, 12, 928000), None, 100, 'ASSIGNMENT', 'ALL_STUDENTS', 'MODIFIABLE_UNTIL_TURNED_IN', '104144867849088240281', None), ('222689364757', '229324082553', 'Commercial Script ', 'Directions inside', 'PUBLISHED', 'https://classroom.google.com/c/MjIyNjg5MzY0NzU3/a/MjI5MzI0MDgyNTUz/details', datetime.datetime(2020, 11, 12, 18, 53, 12, 849000), datetime.datetime(2020, 11, 12, 18, 55, 45, 685000), datetime.datetime(2020, 11, 14, 0, 0), 100, 'ASSIGNMENT', 'ALL_STUDENTS', 'MODIFIABLE_UNTIL_TURNED_IN', '101375802740655167828', None), ('205884161781', '228719101204', 'nez perce', "\nHey it's Thursday already! Bam! You are an overcomer, an overachiever, and blessed with all that you need!  Just like you put your clothes on put l ... (121 characters truncated) ... put your mind and heart into. Con ganas todo se puede! We believe in you! It is better to give than to receive. Being thankful makes your day better!", 'PUBLISHED', 'https://classroom.google.com/c/MjA1ODg0MTYxNzgx/a/MjI4NzE5MTAxMjA0/details', datetime.datetime(2020, 11, 11, 14, 38, 51, 239000), datetime.datetime(2020, 11, 11, 14, 39, 51, 698000), None, 100, 'ASSIGNMENT', 'ALL_STUDENTS', 'MODIFIABLE_UNTIL_TURNED_IN', '105301322954643330860', None), ('205884161781', '228719101157', 'interviw your sibling', "\nHey it's Thursday already! Bam! You are an overcomer, an overachiever, and blessed with all that you need!  Just like you put your clothes on put l ... (121 characters truncated) ... put your mind and heart into. Con ganas todo se puede! We believe in you! It is better to give than to receive. Being thankful makes your day better!", 'PUBLISHED', 'https://classroom.google.com/c/MjA1ODg0MTYxNzgx/a/MjI4NzE5MTAxMTU3/details', datetime.datetime(2020, 11, 11, 14, 37, 32, 584000), datetime.datetime(2020, 11, 11, 14, 37, 49, 542000), None, 100, 'ASSIGNMENT', 'ALL_STUDENTS', 'MODIFIABLE_UNTIL_TURNED_IN', '105301322954643330860', None), ('205884161781', '223029072321', "what did you learn about the labraant family today are they still famouse i don't know you need to answer that question", 'today if you watch the video about the labrant family  well then you would have no problem with this question you needed two wtch both of the video if you took the test if you have not go take the test then aswer this question', 'PUBLISHED', 'https://classroom.google.com/c/MjA1ODg0MTYxNzgx/sa/MjIzMDI5MDcyMzIx/details', datetime.datetime(2020, 11, 11, 13, 36, 30, 870000), datetime.datetime(2020, 11, 11, 13, 39, 35, 641000), None, 100, 'SHORT_ANSWER_QUESTION', 'ALL_STUDENTS', 'MODIFIABLE_UNTIL_TURNED_IN', '105301322954643330860', None)  ... displaying 10 of 2227 total bound parameter sets ...  ('202185157887', '230526788854', 'basketball', 'look at it', 'PUBLISHED', 'https://classroom.google.com/c/MjAyMTg1MTU3ODg3/a/MjMwNTI2Nzg4ODU0/details', datetime.datetime(2020, 11, 16, 13, 31, 25, 455000), datetime.datetime(2020, 11, 16, 13, 31, 22, 341000), datetime.datetime(2020, 11, 19, 5, 59), 100, 'ASSIGNMENT', 'ALL_STUDENTS', 'MODIFIABLE_UNTIL_TURNED_IN', '110665100727005067242', '230526788855'), ('202185157887', '229922436189', 'idk', None, 'PUBLISHED', 'https://classroom.google.com/c/MjAyMTg1MTU3ODg3/a/MjI5OTIyNDM2MTg5/details', datetime.datetime(2020, 11, 13, 20, 35, 49, 875000), datetime.datetime(2020, 11, 13, 20, 35, 51, 242000), None, 100, 'ASSIGNMENT', 'ALL_STUDENTS', 'MODIFIABLE_UNTIL_TURNED_IN', '110665100727005067242', None))]
(Background on this error at: http://sqlalche.me/e/13/9h9h)
Traceback (most recent call last):
  File "C:\Users\WBartley\.virtualenvs\google_classroom-J9HVh9GF\lib\site-packages\sqlalchemy\engine\base.py", line 1258, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\WBartley\.virtualenvs\google_classroom-J9HVh9GF\lib\site-packages\sqlalchemy\dialects\mssql\pyodbc.py", line 417, in do_executemany
    cursor, statement, parameters, context=context
  File "C:\Users\WBartley\.virtualenvs\google_classroom-J9HVh9GF\lib\site-packages\sqlalchemy\engine\default.py", line 590, in do_executemany
    cursor.executemany(statement, parameters)
pyodbc.DataError: ('22018', '[22018] [Microsoft][ODBC Driver 13 for SQL Server]Invalid character value for cast specification (0) (SQLParamData)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 171, in <module>
    main(Config)
  File "main.py", line 150, in main
    CourseWork(classroom_service, sql, config).batch_pull_data(course_ids)
  File "S:\Projects\google_classroom\timer.py", line 22, in wrapper
    results = func(*args, **kwargs)
  File "S:\Projects\google_classroom\api.py", line 259, in batch_pull_data
    self._write_to_db(df)
  File "S:\Projects\google_classroom\api.py", line 96, in _write_to_db
    self.sql.insert_into(self.table_name, df, chunksize=10000)
  File "C:\Users\WBartley\.virtualenvs\google_classroom-J9HVh9GF\lib\site-packages\sqlsorcery\__init__.py", line 210, in insert_into
    dtype=dtype,
  File "C:\Users\WBartley\.virtualenvs\google_classroom-J9HVh9GF\lib\site-packages\pandas\core\generic.py", line 2663, in to_sql
    method=method,
  File "C:\Users\WBartley\.virtualenvs\google_classroom-J9HVh9GF\lib\site-packages\pandas\io\sql.py", line 521, in to_sql
    method=method,
  File "C:\Users\WBartley\.virtualenvs\google_classroom-J9HVh9GF\lib\site-packages\pandas\io\sql.py", line 1317, in to_sql
    table.insert(chunksize, method=method)
  File "C:\Users\WBartley\.virtualenvs\google_classroom-J9HVh9GF\lib\site-packages\pandas\io\sql.py", line 755, in insert
    exec_insert(conn, keys, chunk_iter)
  File "C:\Users\WBartley\.virtualenvs\google_classroom-J9HVh9GF\lib\site-packages\pandas\io\sql.py", line 669, in _execute_insert
    conn.execute(self.table.insert(), data)
  File "C:\Users\WBartley\.virtualenvs\google_classroom-J9HVh9GF\lib\site-packages\sqlalchemy\engine\base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "C:\Users\WBartley\.virtualenvs\google_classroom-J9HVh9GF\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\WBartley\.virtualenvs\google_classroom-J9HVh9GF\lib\site-packages\sqlalchemy\engine\base.py", line 1133, in _execute_clauseelement
    distilled_params,
  File "C:\Users\WBartley\.virtualenvs\google_classroom-J9HVh9GF\lib\site-packages\sqlalchemy\engine\base.py", line 1318, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\WBartley\.virtualenvs\google_classroom-J9HVh9GF\lib\site-packages\sqlalchemy\engine\base.py", line 1512, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "C:\Users\WBartley\.virtualenvs\google_classroom-J9HVh9GF\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\Users\WBartley\.virtualenvs\google_classroom-J9HVh9GF\lib\site-packages\sqlalchemy\engine\base.py", line 1258, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\WBartley\.virtualenvs\google_classroom-J9HVh9GF\lib\site-packages\sqlalchemy\dialects\mssql\pyodbc.py", line 417, in do_executemany
    cursor, statement, parameters, context=context
  File "C:\Users\WBartley\.virtualenvs\google_classroom-J9HVh9GF\lib\site-packages\sqlalchemy\engine\default.py", line 590, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.DataError: (pyodbc.DataError) ('22018', '[22018] [Microsoft][ODBC Driver 13 for SQL Server]Invalid character value for cast specification (0) (SQLParamData)')
[SQL: INSERT INTO dbo.[GoogleClassroom_CourseWork] ([courseId], id, title, description, state, [alternateLink], [creationTime], [updateTime], [dueDate], [maxPoints], [workType], [assigneeMode], [submissionModificationMode], [creatorUserId], [topicId]) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (('222693886482', '223016268500', 'to do', None, 'PUBLISHED', 'https://classroom.google.com/c/MjIyNjkzODg2NDgy/a/MjIzMDE2MjY4NTAw/details', datetime.datetime(2020, 11, 11, 13, 29, 5, 499000), datetime.datetime(2020, 11, 11, 13, 31, 44, 627000), None, 100, 'ASSIGNMENT', 'ALL_STUDENTS', 'MODIFIABLE_UNTIL_TURNED_IN', '115624344439250234383', None), ('222693886482', '222718588596', 'class class', None, 'PUBLISHED', 'https://classroom.google.com/c/MjIyNjkzODg2NDgy/a/MjIyNzE4NTg4NTk2/details', datetime.datetime(2020, 11, 10, 20, 16, 31, 164000), datetime.datetime(2020, 11, 10, 20, 16, 44, 358000), None, 100, 'ASSIGNMENT', 'ALL_STUDENTS', 'MODIFIABLE_UNTIL_TURNED_IN', '115624344439250234383', None), ('222691921702', '232238999150', 'How much wood would a woodchuck chuck if a woodchuck could chuck wood?', 'ANSWER THE QUESTION!', 'PUBLISHED', 'https://classroom.google.com/c/MjIyNjkxOTIxNzAy/sa/MjMyMjM4OTk5MTUw/details', datetime.datetime(2020, 11, 19, 13, 44, 26, 403000), datetime.datetime(2020, 11, 19, 13, 48, 37, 97000), None, 70, 'SHORT_ANSWER_QUESTION', 'ALL_STUDENTS', 'MODIFIABLE_UNTIL_TURNED_IN', '104144867849088240281', None), ('222691921702', '228735845599', 'SPELL IT RIGHT!', 'You have to spell  all the questions right!', 'PUBLISHED', 'https://classroom.google.com/c/MjIyNjkxOTIxNzAy/a/MjI4NzM1ODQ1NTk5/details', datetime.datetime(2020, 11, 11, 15, 24, 38, 974000), datetime.datetime(2020, 11, 11, 15, 39, 12, 928000), None, 100, 'ASSIGNMENT', 'ALL_STUDENTS', 'MODIFIABLE_UNTIL_TURNED_IN', '104144867849088240281', None), ('222689364757', '229324082553', 'Commercial Script ', 'Directions inside', 'PUBLISHED', 'https://classroom.google.com/c/MjIyNjg5MzY0NzU3/a/MjI5MzI0MDgyNTUz/details', datetime.datetime(2020, 11, 12, 18, 53, 12, 849000), datetime.datetime(2020, 11, 12, 18, 55, 45, 685000), datetime.datetime(2020, 11, 14, 0, 0), 100, 'ASSIGNMENT', 'ALL_STUDENTS', 'MODIFIABLE_UNTIL_TURNED_IN', '101375802740655167828', None), ('205884161781', '228719101204', 'nez perce', "\nHey it's Thursday already! Bam! You are an overcomer, an overachiever, and blessed with all that you need!  Just like you put your clothes on put l ... (121 characters truncated) ... put your mind and heart into. Con ganas todo se puede! We believe in you! It is better to give than to receive. Being thankful makes your day better!", 'PUBLISHED', 'https://classroom.google.com/c/MjA1ODg0MTYxNzgx/a/MjI4NzE5MTAxMjA0/details', datetime.datetime(2020, 11, 11, 14, 38, 51, 239000), datetime.datetime(2020, 11, 11, 14, 39, 51, 698000), None, 100, 'ASSIGNMENT', 'ALL_STUDENTS', 'MODIFIABLE_UNTIL_TURNED_IN', '105301322954643330860', None), ('205884161781', '228719101157', 'interviw your sibling', "\nHey it's Thursday already! Bam! You are an overcomer, an overachiever, and blessed with all that you need!  Just like you put your clothes on put l ... (121 characters truncated) ... put your mind and heart into. Con ganas todo se puede! We believe in you! It is better to give than to receive. Being thankful makes your day better!", 'PUBLISHED', 'https://classroom.google.com/c/MjA1ODg0MTYxNzgx/a/MjI4NzE5MTAxMTU3/details', datetime.datetime(2020, 11, 11, 14, 37, 32, 584000), datetime.datetime(2020, 11, 11, 14, 37, 49, 542000), None, 100, 'ASSIGNMENT', 'ALL_STUDENTS', 'MODIFIABLE_UNTIL_TURNED_IN', '105301322954643330860', None), ('205884161781', '223029072321', "what did you learn about the labraant family today are they still famouse i don't know you need to answer that question", 'today if you watch the video about the labrant family  well then you would have no problem with this question you needed two wtch both of the video if you took the test if you have not go take the test then aswer this question', 'PUBLISHED', 'https://classroom.google.com/c/MjA1ODg0MTYxNzgx/sa/MjIzMDI5MDcyMzIx/details', datetime.datetime(2020, 11, 11, 13, 36, 30, 870000), datetime.datetime(2020, 11, 11, 13, 39, 35, 641000), None, 100, 'SHORT_ANSWER_QUESTION', 'ALL_STUDENTS', 'MODIFIABLE_UNTIL_TURNED_IN', '105301322954643330860', None)  ... displaying 10 of 2227 total bound parameter sets ...  ('202185157887', '230526788854', 'basketball', 'look at it', 'PUBLISHED', 'https://classroom.google.com/c/MjAyMTg1MTU3ODg3/a/MjMwNTI2Nzg4ODU0/details', datetime.datetime(2020, 11, 16, 13, 31, 25, 455000), datetime.datetime(2020, 11, 16, 13, 31, 22, 341000), datetime.datetime(2020, 11, 19, 5, 59), 100, 'ASSIGNMENT', 'ALL_STUDENTS', 'MODIFIABLE_UNTIL_TURNED_IN', '110665100727005067242', '230526788855'), ('202185157887', '229922436189', 'idk', None, 'PUBLISHED', 'https://classroom.google.com/c/MjAyMTg1MTU3ODg3/a/MjI5OTIyNDM2MTg5/details', datetime.datetime(2020, 11, 13, 20, 35, 49, 875000), datetime.datetime(2020, 11, 13, 20, 35, 51, 242000), None, 100, 'ASSIGNMENT', 'ALL_STUDENTS', 'MODIFIABLE_UNTIL_TURNED_IN', '110665100727005067242', None))]
(Background on this error at: http://sqlalche.me/e/13/9h9h)

**Comment by zkagin** [comment]
Thanks for raising this, @KTXDataSystems. It looks like there is some assignment data which either has an odd type of data or a character that the database is struggling to parse. Without access to the data you have, I will have a hard time reproducing it, but I can make some changes that will at least allow for uploading of non-problematic data and print out what data is the problem. How urgent of an issue is this for you?

In the mean time, if you are able to use the Google Classroom UI to scan through the student submissions and/or coursework made since you last pulled data, we might be able to pinpoint something weird happening?

**Comment by KTXDataSystems** [comment]
Hi Zach,

Thanks for taking a look into this.  A little tiny bit of background – around the beginning of November we started getting errors downloading the CourseWork that appeared to be due to a bad date.  There’s an issue for that, too.  But, we could live with that because the real important piece we needed was the Student Submission data which continued to work.    Then the person that monitored this data went on leave for a couple weeks.  When she came back she noticed the Student Submission stopped, too.  We did pull some of the errors like I submitted and looked into the specific assignments and were able to fix a few.  For instance, we found coursework that was created, but not all fields filled in and that cleared some errors, but when we got to the ones I submitted, we were unable to find anything obvious to fix in GC.

I’d be happy to help you get access to the data one way or another.  I’d also really appreciate any changes that could print out the problem data so we can fix it up and / or allow uploading the ‘good’ data.  Either or both would be extremely helpful.  As for access, probably the easiest(?) thing would be to share a screen and give you control or let you walk me through things?  Thoughts?


William Bartley
KTX Director, Data Systems

[cid:image011.png@01D65E6D.53DAE930]<http://www.kipptexas.org/>

KIPP Texas Public Schools
8509 FM 969 Building 619 | Austin, TX 78724
E: william.bartley@kipptexas.org<mailto:william.bartley@kipptexas.org>
C: 512.983.0724

[cid:image012.png@01D65E6D.53DAE930]<http://www.kipptexas.org/>  [cid:image013.png@01D65E6D.53DAE930] <http://www.facebook.com/kipptexas>   [cid:image014.png@01D65E6D.53DAE930] <http://www.instagram.com/kipptexas>   [cid:image015.png@01D65E6D.53DAE930] <http://www.twitter.com/kipptexas>

**Comment by zkagin** [comment]
@KTXDataSystems Thanks for the additional detail William. I have made a patch #117 that should help us find the bad data, at the very least. I was unable to reproduce this error via special characters or missing data, which makes me think it may have to do with a specific database configuration you are using. Once we know exactly what data is breaking it, that should at least help us try and reproduce the error.

To use this code, you can download the updated code at https://github.com/kippnorcal/google_classroom/tree/find_bad_data.

**Comment by KTXDataSystems** [comment]
Well, now I can see errors!   I will try to start cleaning them up.  Here’s the first – it’s trying to insert this pair into the coursework table:  [maxpoints] : ‘Infinity’ – the maxpoints column is a float.

Wondering if it would be possible to make it log those errors (even if just to the screen) and continue on?  A million thanks either way.

--Bill

**Comment by zkagin** [comment]
@KTXDataSystems Glad we can start to see errors. Yep, maxpoints being Infinity definitely isn't expected, so we aren't handling that well. Are you coming across any other errors, or just that one?

With the patch, it should print these errors on the screen and keep going. Let me know if it does not do that and I can see what might be happening. Once we confirm the different errors you have, I'll add some additional code to handle those so we can upload these rows as well.

**Comment by KTXDataSystems** [comment]
Zach,

Can we connect through normal email or maybe a quick call at some point?  I have some other questions about the tool and may need some additional support implementing the new changes.

I really do appreciate your help and support.


William Bartley
KTX Director, Data Systems

[cid:image011.png@01D65E6D.53DAE930]<http://www.kipptexas.org/>

KIPP Texas Public Schools
8509 FM 969 Building 619 | Austin, TX 78724
E: william.bartley@kipptexas.org<mailto:william.bartley@kipptexas.org>
C: 512.983.0724

[cid:image012.png@01D65E6D.53DAE930]<http://www.kipptexas.org/>  [cid:image013.png@01D65E6D.53DAE930] <http://www.facebook.com/kipptexas>   [cid:image014.png@01D65E6D.53DAE930] <http://www.instagram.com/kipptexas>   [cid:image015.png@01D65E6D.53DAE930] <http://www.twitter.com/kipptexas>

**Comment by zkagin** [comment]
@KTXDataSystems Not a problem. My email should be in my profile, please feel free to reach out there.
