### ISSUE TITLE
Purpose of draftGrade and draftGraderID?

### ISSUE THREAD

**Issue by bkimup** [kippnorcal/google_classroom#118]
Is there any reason for parsing the StudentSubmission data to get data related to the draft of student work as opposed to saving just one single grade, regardless of its state? Would it be bad practice to have the draft grade as a student's reported grade until a teacher grades and returns the assignment?

**Comment by dchess** [comment]
The rationale here in pulling both is to allow for flexibility on how to address that. That can be handled on the SQL or analysis side if different people want to approach that differently.
