### ISSUE TITLE
SQL Deadlocks

### ISSUE THREAD

**Issue by dchess** [kippnorcal/google_classroom#120]
A few of the endpoints are starting to encounter deadlocks when writing to the database:

```
ERROR: (pyodbc.Error) ('40001', '[40001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Transaction (Process ID 51) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction. (1205) (SQLExecDirectW)')

[SQL: SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] 
FROM [INFORMATION_SCHEMA].[TABLES] 
WHERE [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) ORDER BY [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]]

[parameters: ('custom', 'BASE TABLE')]
(Background on this error at: http://sqlalche.me/e/13/dbapi)

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
pyodbc.Error: ('40001', '[40001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Transaction (Process ID 51) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction. (1205) (SQLExecDirectW)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 172, in <module>
    main(Config)
  File "main.py", line 69, in main
    pull_data(config, creds, sql)
  File "main.py", line 157, in pull_data
    StudentSubmissions(classroom_service, sql, config).batch_pull_data(course_ids)
 File "/google_classroom/timer.py", line 22, in wrapper
    results = func(*args, **kwargs)
  File "/google_classroom/endpoints/base.py", line 268, in batch_pull_data
    self._write_to_db(df)
  File "/google_classroom/endpoints/base.py", line 98, in _write_to_db
    self.sql.insert_into(self.table_name, df, chunksize=10000)
```

This might require some retry logic to `_write_to_db()`.

**Comment by dchess** [comment]
@zkagin I confirmed this is not a timing issue where there's a collision with another query or process. I'm wondering if the batches are somehow trying to write simultaneously?

**Comment by zkagin** [comment]
@dchess How consistent or reproducible is this? Any specific Google endpoints this tends to fail on? I'm wondering if pandas is breaking up the writes into chunks of 10K and parallelizing those, causing the deadlock. If we manually break that up and do it in series instead, that would avoid the problem.

**Comment by dchess** [comment]
@zkagin its been consistently failing nightly but will run if I rerun manually (most of the time, sometimes it still gets the error). Its happening on all the endpoints but not consistent.  Sometimes its coursework and submissions. Other times courses or students. 

Deadlocking is usually a timing thing, wondering if just wrapping the db write method in a retry would be a worthwhile approach.

**Comment by zkagin** [comment]
Deadlocking is a timing issue, but that timing requires some concurrency — there has to be something else also locking the database, and I don't see any other concurrent calls.

I'm not able to repro myself, but some more thoughts:

https://stackoverflow.com/questions/41900988/sql-server-pyodbc-and-deadlock-errors has some interesting insights into this, where the transaction might actually be conflicting with itself in some form. Explicitly ending transactions or using autocommit might work here? Depending on how pandas handles commits, we could also break up the commit ourselves into smaller chunks, or vary the chunksize parameter to see if that helps.
